/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness: the process answers.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness: the database answers.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Prometheus metrics (loopback-only by default, like the rest of the API).
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status
         * @description Whether first-run setup is needed and whether this browser is signed in. Returns the CSRF
         *     token for the signed-in session (the UI keeps it in memory, not in storage).
         */
        get: operations["status_api_auth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Setup
         * @description Create the admin account. Only possible while no account exists.
         */
        post: operations["setup_api_auth_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Change the password and sign out every other session.
         */
        post: operations["change_password_api_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensor/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capabilities
         * @description Whether this machine can capture, which backend will be used, and how to fix problems.
         */
        get: operations["capabilities_api_sensor_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensor/interfaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Interfaces
         * @description Capture interfaces: adapters with a routable IPv4 address first, loopback last.
         */
        get: operations["interfaces_api_sensor_interfaces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensor/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_sensor_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensor/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start
         * @description Start capturing on an interface, with the active model (if any).
         */
        post: operations["start_api_sensor_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensor/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop
         * @description Stop capturing. Open flows are flushed and the session is closed before the sensor exits.
         */
        post: operations["stop_api_sensor_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description Alerts, most recently active first, filtered and paginated.
         */
        get: operations["list_alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alert */
        get: operations["get_alert_api_alerts__alert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Alert
         * @description Acknowledge, resolve or mark as false positive (which also suppresses repeats), and/or
         *     change the note.
         */
        patch: operations["update_alert_api_alerts__alert_id__patch"];
        trace?: never;
    };
    "/api/flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Flows */
        get: operations["list_flows_api_flows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Timeseries
         * @description Traffic per second (resolution=1, last 24 h) or per minute (resolution=60), summed over
         *     sessions unless one is given. Replays keep their original timestamps; pass their session.
         */
        get: operations["timeseries_api_stats_timeseries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summary
         * @description Numbers for the Overview KPI strip.
         */
        get: operations["summary_api_stats_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Runtime Settings */
        get: operations["get_runtime_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Runtime Settings
         * @description Change some settings. Unknown keys and out-of-range values are rejected (audit SEC-02).
         */
        patch: operations["update_runtime_settings_api_settings_patch"];
        trace?: never;
    };
    "/api/suppressions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_suppressions_get"];
        put?: never;
        /** Add Rule */
        post: operations["add_rule_api_suppressions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppressions/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disable Rule */
        delete: operations["disable_rule_api_suppressions__rule_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Uploads */
        get: operations["list_uploads_api_uploads_get"];
        put?: never;
        /**
         * Upload Pcap
         * @description Upload a pcap/pcapng file for replay. Stored under its own id; the file's type is checked
         *     by its signature, not its name (audit SEC-04).
         */
        post: operations["upload_pcap_api_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /** Start Job */
        post: operations["start_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Logs
         * @description Tail of the API log, or of one job's log (`job:<id>`, e.g. the sensor's).
         */
        get: operations["logs_api_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Log */
        get: operations["audit_log_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{version}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate
         * @description Use this model the next time the sensor starts.
         */
        post: operations["activate_api_models__version__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deactivate
         * @description Run the sensor with heuristics only.
         */
        post: operations["deactivate_api_models_deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertOut */
        AlertOut: {
            /** Id */
            id: string;
            /** Session Id */
            session_id: string | null;
            /** Created At */
            created_at: number;
            /** Last Seen */
            last_seen: number;
            /** Updated At */
            updated_at: number;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Source */
            source: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "low" | "medium" | "high" | "critical";
            /** Confidence */
            confidence: number;
            /** Src */
            src: string | null;
            /** Dst */
            dst: string | null;
            /** Ports */
            ports: number[];
            /** Protocol */
            protocol: number | null;
            /** Mitre Technique */
            mitre_technique: string | null;
            /** Explanation */
            explanation: string;
            /** Recommendation */
            recommendation: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /** Occurrences */
            occurrences: number;
            /** Flow Ids */
            flow_ids: string[];
            /** Family */
            family: string | null;
            /** Model Version */
            model_version: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "acknowledged" | "resolved" | "false_positive";
            /** Note */
            note: string;
        };
        /** AlertUpdate */
        AlertUpdate: {
            /** Status */
            status?: ("new" | "acknowledged" | "resolved" | "false_positive") | null;
            /** Note */
            note?: string | null;
        };
        /** AuthStatus */
        AuthStatus: {
            /** Setup Required */
            setup_required: boolean;
            /** Authenticated */
            authenticated: boolean;
            /** Username */
            username?: string | null;
            /** Csrf Token */
            csrf_token?: string | null;
        };
        /** Body_upload_pcap_api_uploads_post */
        Body_upload_pcap_api_uploads_post: {
            /** File */
            file: string;
        };
        /** Bucket */
        Bucket: {
            /** Ts */
            ts: number;
            /** Packets */
            packets: number;
            /** Bytes */
            bytes: number;
            /** Tcp */
            tcp: number;
            /** Udp */
            udp: number;
            /** Icmp */
            icmp: number;
            /** Other */
            other: number;
            /** Flows Started */
            flows_started: number;
            /** Flows Ended */
            flows_ended: number;
            /** Alerts */
            alerts: number;
        };
        /** CapabilityReport */
        CapabilityReport: {
            /** Platform */
            platform: string;
            /** Backend */
            backend: ("nfstream" | "scapy") | null;
            /** Checks */
            checks: components["schemas"]["Check"][];
            /** Ok */
            readonly ok: boolean;
        };
        /** Check */
        Check: {
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "warning" | "error";
            /** Detail */
            detail: string;
            /** Fix */
            fix?: string | null;
        };
        /** Credentials */
        Credentials: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** FlowOut */
        FlowOut: {
            /** Id */
            id: number;
            /** Session Id */
            session_id: string;
            /** Flow Id */
            flow_id: string;
            /** First Seen */
            first_seen: number;
            /** Last Seen */
            last_seen: number;
            /** Src Ip */
            src_ip: string;
            /** Dst Ip */
            dst_ip: string;
            /** Src Port */
            src_port: number;
            /** Dst Port */
            dst_port: number;
            /** Protocol */
            protocol: number;
            /** Packets */
            packets: number;
            /** Payload Bytes */
            payload_bytes: number;
            /** Ip Bytes */
            ip_bytes: number | null;
            /** End Reason */
            end_reason: string;
            /** App Protocol */
            app_protocol: string | null;
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InterfaceInfo */
        InterfaceInfo: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Ipv4 */
            ipv4: string[];
            /** Ipv6 */
            ipv6: string[];
            /** Mac */
            mac: string | null;
            /** Loopback */
            loopback: boolean;
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /** Created At */
            created_at: number;
            /** Started At */
            started_at: number | null;
            /** Finished At */
            finished_at: number | null;
            /** Exit Code */
            exit_code: number | null;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Created By */
            created_by: string;
        };
        /** ModelOut */
        ModelOut: {
            /** Version */
            version: string;
            /** Created At */
            created_at: number;
            /** Dataset */
            dataset: string | null;
            /** Protocol */
            protocol: string | null;
            /** Feature Set */
            feature_set: string | null;
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Active */
            active: boolean;
        };
        /** Page[AlertOut] */
        Page_AlertOut_: {
            /** Items */
            items: components["schemas"]["AlertOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[FlowOut] */
        Page_FlowOut_: {
            /** Items */
            items: components["schemas"]["FlowOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[SessionOut] */
        Page_SessionOut_: {
            /** Items */
            items: components["schemas"]["SessionOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PasswordChange */
        PasswordChange: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** PrepareJob */
        PrepareJob: {
            /**
             * Kind
             * @constant
             */
            kind: "prepare";
            /**
             * Dataset
             * @enum {string}
             */
            dataset: "cicids2017" | "unsw-nb15";
        };
        /** ReplayJob */
        ReplayJob: {
            /**
             * Kind
             * @constant
             */
            kind: "replay";
            /** Upload Id */
            upload_id: string;
            /**
             * Use Model
             * @default true
             */
            use_model: boolean;
        };
        /** RuleIn */
        RuleIn: {
            /** Type */
            type?: string | null;
            /** Src */
            src?: string | null;
            /** Dst */
            dst?: string | null;
            /** Dst Port */
            dst_port?: number | null;
            /** Until */
            until?: number | null;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** RuleOut */
        RuleOut: {
            /** Type */
            type?: string | null;
            /** Src */
            src?: string | null;
            /** Dst */
            dst?: string | null;
            /** Dst Port */
            dst_port?: number | null;
            /** Until */
            until?: number | null;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Id */
            id: number;
            /** Created At */
            created_at: number;
            /** Created By */
            created_by: string;
            /** Active */
            active: boolean;
            /** Alert Id */
            alert_id: string | null;
        };
        /** RuntimeSettings */
        RuntimeSettings: {
            /**
             * Scan Window S
             * @description Port scan / sweep time window
             * @default 30
             */
            scan_window_s: number;
            /**
             * Scan Min Ports
             * @description Ports on one host to call it a scan
             * @default 25
             */
            scan_min_ports: number;
            /**
             * Sweep Min Hosts
             * @description Hosts in one subnet to call it a sweep
             * @default 20
             */
            sweep_min_hosts: number;
            /**
             * Flood Min Syn Rate
             * @description SYNs/s floor for a SYN flood
             * @default 100
             */
            flood_min_syn_rate: number;
            /**
             * Flood Min Pps
             * @description Packets/s floor for a UDP/ICMP flood
             * @default 5000
             */
            flood_min_pps: number;
            /**
             * Flood Z
             * @description Standard deviations above normal for a flood
             * @default 6
             */
            flood_z: number;
            /**
             * Allowed Protocols
             * @description IP protocols that never alert
             * @default [
             *       1,
             *       2,
             *       6,
             *       17,
             *       58
             *     ]
             */
            allowed_protocols: number[];
            /**
             * Dedup Window S
             * @description Merge repeats of an alert within this window
             * @default 900
             */
            dedup_window_s: number;
            /**
             * Flow Sample Rate
             * @description Share of flows stored
             * @default 1
             */
            flow_sample_rate: number;
            /**
             * Attack Threshold
             * @description Classifier threshold (None = model default)
             */
            attack_threshold?: number | null;
            /**
             * Novelty Threshold
             * @description Novelty threshold (None = model default)
             */
            novelty_threshold?: number | null;
            /**
             * Retention Flows Days
             * @description Keep flows this long
             * @default 7
             */
            retention_flows_days: number;
            /**
             * Retention Alerts Days
             * @description Keep alerts this long
             * @default 90
             */
            retention_alerts_days: number;
            /**
             * Pseudonymize Ips
             * @description Store IP addresses as keyed hashes
             * @default false
             */
            pseudonymize_ips: boolean;
        };
        /** SensorState */
        SensorState: {
            /** Running */
            running: boolean;
            /** Job Id */
            job_id: string | null;
            /** Pid */
            pid: number | null;
            /** Interface */
            interface: string | null;
            /** Session Id */
            session_id: string | null;
            /** Started At */
            started_at: number | null;
            /** Model Version */
            model_version: string | null;
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Source */
            source: string;
            /** Backend */
            backend: string;
            /** Model Version */
            model_version: string | null;
            /** Started At */
            started_at: number;
            /** Stopped At */
            stopped_at: number | null;
            /** Status */
            status: string;
            /** Error */
            error: string | null;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
        };
        /** SettingsOut */
        SettingsOut: {
            values: components["schemas"]["RuntimeSettings"];
            /** Apply */
            apply: {
                [key: string]: string;
            };
        };
        /** SetupRequest */
        SetupRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** StartSensor */
        StartSensor: {
            /** Interface */
            interface: string;
            /**
             * Backend
             * @default auto
             * @enum {string}
             */
            backend: "auto" | "scapy" | "nfstream";
        };
        /** Summary */
        Summary: {
            /** Open Alerts */
            open_alerts: {
                [key: string]: number;
            };
            /** Alerts Last 24H */
            alerts_last_24h: number;
            /** Flows Last Hour */
            flows_last_hour: number;
            /** Top Talkers */
            top_talkers: {
                [key: string]: unknown;
            }[];
            /** Protocols Last 15M */
            protocols_last_15m: {
                [key: string]: number;
            };
        };
        /** TrainJob */
        TrainJob: {
            /**
             * Kind
             * @constant
             */
            kind: "train";
            /**
             * Dataset
             * @enum {string}
             */
            dataset: "cicids2017" | "unsw-nb15";
            /**
             * Protocol
             * @default day
             * @enum {string}
             */
            protocol: "day" | "random" | "official";
            /**
             * Features
             * @default full
             * @enum {string}
             */
            features: "full" | "shared";
            /** Sample Frac */
            sample_frac?: number | null;
        };
        /** UploadOut */
        UploadOut: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Size */
            size: number;
            /** Sha256 */
            sha256: string;
            /** Format */
            format: string;
            /** Created At */
            created_at: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    status_api_auth_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    setup_api_auth_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    change_password_api_auth_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_api_sensor_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityReport"];
                };
            };
        };
    };
    interfaces_api_sensor_interfaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterfaceInfo"][];
                };
            };
        };
    };
    status_api_sensor_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorState"];
                };
            };
        };
    };
    start_api_sensor_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSensor"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_api_sensor_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorState"];
                };
            };
        };
    };
    list_alerts_api_alerts_get: {
        parameters: {
            query?: {
                severity?: ("info" | "low" | "medium" | "high" | "critical")[];
                status?: ("new" | "acknowledged" | "resolved" | "false_positive")[];
                type?: string[];
                src?: string | null;
                dst?: string | null;
                since?: number | null;
                until?: number | null;
                session_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AlertOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_api_alerts__alert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_alert_api_alerts__alert_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_flows_api_flows_get: {
        parameters: {
            query?: {
                session_id?: string | null;
                /** @description Either endpoint */
                ip?: string | null;
                port?: number | null;
                protocol?: number | null;
                flow_id?: string[];
                since?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_FlowOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SessionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeseries_api_stats_timeseries_get: {
        parameters: {
            query?: {
                resolution?: 1 | 60;
                /** @description Epoch seconds; default: last 15 min */
                since?: number | null;
                session_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bucket"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_stats_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
        };
    };
    get_runtime_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    update_runtime_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_suppressions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"][];
                };
            };
        };
    };
    add_rule_api_suppressions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_rule_api_suppressions__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_uploads_api_uploads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"][];
                };
            };
        };
    };
    upload_pcap_api_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_pcap_api_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplayJob"] | components["schemas"]["TrainJob"] | components["schemas"]["PrepareJob"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logs_api_logs_get: {
        parameters: {
            query?: {
                source?: string;
                lines?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_log_api_audit_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOut"][];
                };
            };
        };
    };
    activate_api_models__version__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_api_models_deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: null;
                    };
                };
            };
        };
    };
}
