"""initial schema

Revision ID: 28e8db6c7498
Revises:
Create Date: 2026-09-22 18:17:10.775161
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "28e8db6c7498"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.Float(), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=128), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_ts"), ["ts"], unique=False)

    op.create_table(
        "models",
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("registered_at", sa.Float(), nullable=False),
        sa.Column("dataset", sa.String(length=64), nullable=True),
        sa.Column("protocol", sa.String(length=32), nullable=True),
        sa.Column("feature_set", sa.String(length=32), nullable=True),
        sa.Column("schema_hash", sa.String(length=32), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("version", name=op.f("pk_models")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=512), nullable=False),
        sa.Column("backend", sa.String(length=16), nullable=False),
        sa.Column("model_version", sa.String(length=128), nullable=True),
        sa.Column("started_at", sa.Float(), nullable=False),
        sa.Column("stopped_at", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "suppression_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type", sa.String(length=32), nullable=True),
        sa.Column("src", sa.String(length=64), nullable=True),
        sa.Column("dst", sa.String(length=64), nullable=True),
        sa.Column("dst_port", sa.Integer(), nullable=True),
        sa.Column("until", sa.Float(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("alert_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppression_rules")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("last_login_at", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("last_seen", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("src", sa.String(length=64), nullable=True),
        sa.Column("dst", sa.String(length=64), nullable=True),
        sa.Column("ports", sa.JSON(), nullable=False),
        sa.Column("protocol", sa.Integer(), nullable=True),
        sa.Column("mitre_technique", sa.String(length=128), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("occurrences", sa.Integer(), nullable=False),
        sa.Column("flow_ids", sa.JSON(), nullable=False),
        sa.Column("family", sa.String(length=32), nullable=True),
        sa.Column("model_version", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_alerts_session_id_sessions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alerts_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_alerts_severity_status"), ["severity", "status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_alerts_src"), ["src"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_type"), ["type"], unique=False)

    op.create_table(
        "flows",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("flow_id", sa.String(length=64), nullable=False),
        sa.Column("first_seen", sa.Float(), nullable=False),
        sa.Column("last_seen", sa.Float(), nullable=False),
        sa.Column("src_ip", sa.String(length=64), nullable=False),
        sa.Column("dst_ip", sa.String(length=64), nullable=False),
        sa.Column("src_port", sa.Integer(), nullable=False),
        sa.Column("dst_port", sa.Integer(), nullable=False),
        sa.Column("protocol", sa.Integer(), nullable=False),
        sa.Column("packets", sa.Integer(), nullable=False),
        sa.Column("payload_bytes", sa.Integer(), nullable=False),
        sa.Column("ip_bytes", sa.Integer(), nullable=True),
        sa.Column("end_reason", sa.String(length=16), nullable=False),
        sa.Column("app_protocol", sa.String(length=64), nullable=True),
        sa.Column("stats", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_flows_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flows")),
    )
    with op.batch_alter_table("flows", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_flows_dst_ip"), ["dst_ip"], unique=False)
        batch_op.create_index(batch_op.f("ix_flows_flow_id"), ["flow_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_flows_session_id_first_seen"), ["session_id", "first_seen"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_flows_src_ip"), ["src_ip"], unique=False)

    op.create_table(
        "traffic",
        sa.Column("resolution", sa.Integer(), nullable=False),
        sa.Column("ts", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("packets", sa.Integer(), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.Column("tcp", sa.Integer(), nullable=False),
        sa.Column("udp", sa.Integer(), nullable=False),
        sa.Column("icmp", sa.Integer(), nullable=False),
        sa.Column("other", sa.Integer(), nullable=False),
        sa.Column("flows_started", sa.Integer(), nullable=False),
        sa.Column("flows_ended", sa.Integer(), nullable=False),
        sa.Column("alerts", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_traffic_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("resolution", "ts", "session_id", name=op.f("pk_traffic")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("traffic")
    with op.batch_alter_table("flows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_flows_src_ip"))
        batch_op.drop_index(batch_op.f("ix_flows_session_id_first_seen"))
        batch_op.drop_index(batch_op.f("ix_flows_flow_id"))
        batch_op.drop_index(batch_op.f("ix_flows_dst_ip"))

    op.drop_table("flows")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_type"))
        batch_op.drop_index(batch_op.f("ix_alerts_src"))
        batch_op.drop_index(batch_op.f("ix_alerts_severity_status"))
        batch_op.drop_index(batch_op.f("ix_alerts_created_at"))

    op.drop_table("alerts")
    op.drop_table("users")
    op.drop_table("suppression_rules")
    op.drop_table("settings")
    op.drop_table("sessions")
    op.drop_table("models")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_ts"))

    op.drop_table("audit_log")
    # ### end Alembic commands ###
